# 人-AI对话治疗专用配置
# 此文件针对人类治疗师与AI患者的对话场景进行优化

description: "人-AI对话治疗专用配置"

# 治疗有效性参数（人-AI优化）
therapy_effectiveness:
  description: "治疗有效性配置参数"
  
  # 基础改善因子
  # 建议范围: 0.4-0.8
  # 物理意义: 人类治疗师的专业技能带来更高的基础治疗效果
  # 比AI-AI场景更高，体现人类专业优势
  base_improvement_factor: 0.6
  
  # 单轮最大改善幅度
  # 建议范围: 0.8-1.5
  # 物理意义: 人类治疗师能产生更大的单次改善效果
  # 体现人类共情和灵活性的优势
  max_improvement_per_turn: 1.0
  
  # 单轮最小改善幅度
  # 建议范围: 0.1-0.4
  # 物理意义: 即使在困难情况下，人类治疗师仍能产生较好效果
  min_improvement_per_turn: 0.2
  
  # 治疗技术权重
  # 建议范围: 0.3-0.7
  # 物理意义: 人类治疗师技术运用的重要性
  # 较高值体现专业技能的价值
  technique_weight: 0.5
  
  # 患者开放性权重
  # 建议范围: 0.2-0.5
  # 物理意义: 人类治疗师更能激发患者开放性
  # 相对降低，因为人类更善于建立信任
  openness_weight: 0.3
  
  # 治疗联盟权重
  # 建议范围: 0.1-0.3
  # 物理意义: 人类天然的共情能力降低了联盟建立的难度
  # 较低权重体现人类在关系建立方面的天然优势
  connection_weight: 0.2

# CAD认知模型状态变化参数（人-AI优化）
cad_state_changes:
  description: "CAD认知模型状态变化参数"
  
  # 核心信念变化（人类治疗师优化）
  core_beliefs:
    # 自我信念变化率
    # 建议范围: 0.15-0.3
    # 物理意义: 人类治疗师更能促进深层自我认知改变
    self_belief_change_rate: 0.18
    
    # 世界观变化率
    # 建议范围: 0.12-0.25
    # 物理意义: 通过人际互动改变对世界的看法
    world_belief_change_rate: 0.15
    
    # 未来观变化率
    # 建议范围: 0.18-0.35
    # 物理意义: 人类治疗师特别擅长重建希望和未来规划
    future_belief_change_rate: 0.22
    
    # 稳定性因子
    # 建议范围: 0.75-0.85
    # 物理意义: 人类治疗师能促进更深层但稳定的改变
    # 较低值允许更大的积极变化
    stability_factor: 0.80
  
  # 认知处理（人类治疗师优化）
  cognitive_processing:
    # 沉思减少率
    # 建议范围: 0.2-0.4
    # 物理意义: 人类治疗师擅长打断负面思维循环
    rumination_reduction_rate: 0.25
    
    # 认知扭曲减少率
    # 建议范围: 0.15-0.3
    # 物理意义: 通过对话有效识别和纠正认知错误
    distortions_reduction_rate: 0.20
    
    # 积极重构奖励
    # 建议范围: 0.1-0.25
    # 物理意义: 人类治疗师能给予更有效的积极反馈
    positive_reframe_bonus: 0.15
  
  # 行为模式（人类治疗师优化）
  behavioral_patterns:
    # 社交退缩改变率
    # 建议范围: 0.15-0.3
    # 物理意义: 人类榜样作用促进社交行为改善
    social_withdrawal_change_rate: 0.18
    
    # 意志缺失改变率
    # 建议范围: 0.12-0.25
    # 物理意义: 人类激励更能恢复行动动机
    avolition_change_rate: 0.15
    
    # 行为激活奖励
    # 建议范围: 0.08-0.2
    # 物理意义: 人类治疗师能提供更个性化的行为指导
    activation_bonus: 0.12
  
  # 情感基调变化率（人类治疗师优化）
  # 建议范围: 0.2-0.4
  # 物理意义: 人类共情能力对情感状态的强大影响
  affective_tone_change_rate: 0.28
  
  # 治疗响应修正因子（人类治疗师优化）
  # 建议范围: 1.2-1.8
  # 物理意义: 人类治疗情境下的状态变化放大效应
  # 体现人类专业治疗的优越性
  therapy_response_modifier: 1.4
  
  # 修正因子
  # 建议范围: 0.9-0.95
  # 物理意义: 人类治疗师能更好控制变化节奏
  correction_factor: 0.92

# 抑郁程度发展设置（人-AI对话优化）
depression_level_progression:
  description: "抑郁程度变化设置（人-AI对话）"
  
  # 改善阈值
  # 建议范围: 3.0-6.0
  # 物理意义: 人类治疗师效果更好，需要较高阈值防止过快晋级
  improvement_threshold: 4.0
  
  # 恶化阈值
  # 建议范围: 2.0-4.0
  # 物理意义: 人类治疗师更能及时发现和处理恶化
  deterioration_threshold: 2.5
  
  # 等级变化延迟轮数
  # 建议范围: 3-6轮
  # 物理意义: 人类治疗师的高效性允许较快的等级变化
  level_change_delay_turns: 4
  
  # 恢复加速因子
  # 建议范围: 1.3-2.0
  # 物理意义: 人类治疗师的专业优势带来更强的恢复加速
  recovery_acceleration_factor: 1.5

# 督导功能设置（人类治疗师场景）
supervision_settings:
  description: "督导功能设置"
  
  # 督导间隔（轮数）
  # 建议范围: 2-4轮
  # 物理意义: 人类治疗师需要更频繁的专业督导
  supervision_interval: 3
  
  # 评估间隔（轮数）
  # 建议范围: 1-2轮
  # 物理意义: 对人类治疗师表现的密切监控
  evaluation_interval: 1
  
  # 风险阈值
  # 建议范围: 0.6-0.9
  # 物理意义: 人类治疗师的风险识别能力阈值
  # 较高值体现对人类专业判断的信任
  risk_threshold: 0.8
  
  # 进展阈值
  # 建议范围: 0.3-0.6
  # 物理意义: 人类治疗师的最低进展期望
  progress_threshold: 0.4
  
  # 督导深度
  # 建议: "comprehensive"
  # 物理意义: 人类治疗师需要最全面的督导支持
  supervision_depth: "comprehensive"

# 对话专用设置（人-AI场景）
conversation_settings:
  description: "对话专用设置"
  
  # 对话历史长度
  # 建议范围: 15-25轮
  # 物理意义: 人类治疗师能处理更长的对话历史
  conversation_history_length: 20
  
  # 最大显示事件数
  # 建议范围: 15-25个
  # 物理意义: 为人类治疗师提供更丰富的背景信息
  max_events_to_show: 20
  
  # 启用督导
  # 建议: true
  # 物理意义: 人类治疗师需要督导支持
  enable_supervision: true
  
  # 督导分析深度
  # 建议: "COMPREHENSIVE"
  # 物理意义: 为人类治疗师提供最详细的分析
  supervision_analysis_depth: "COMPREHENSIVE"

# 情绪状态动态变化（人类治疗师优化）
emotional_state_dynamics:
  description: "情绪状态动态变化"
  
  # 压力减少率
  # 建议范围: 0.4-0.7
  # 物理意义: 人类治疗师的减压效果更佳
  stress_reduction_rate: 0.5
  
  # 自尊改善率
  # 建议范围: 0.3-0.6
  # 物理意义: 人类肯定和支持对自尊的强大影响
  self_esteem_improvement_rate: 0.4
  
  # 社交联系增强率
  # 建议范围: 0.2-0.5
  # 物理意义: 通过治疗关系改善社交能力
  social_connection_enhancement_rate: 0.3
  
  # 学业压力缓解率
  # 建议范围: 0.2-0.4
  # 物理意义: 人类治疗师提供更具体的应对策略
  academic_pressure_relief_rate: 0.25

# 不同治疗技术的效果权重（人类治疗师优化）
therapy_techniques_effectiveness:
  description: "不同治疗技术的效果权重"
  
  # 认知重构技术
  # 建议范围: 0.8-1.0
  # 物理意义: 人类治疗师的认知重构技能最为有效
  cognitive_restructuring: 0.9
  
  # 情感验证技术
  # 建议范围: 0.6-0.9
  # 物理意义: 人类天然的共情优势
  emotional_validation: 0.7
  
  # 行为激活技术
  # 建议范围: 0.7-1.0
  # 物理意义: 人类治疗师能提供更个性化的行为指导
  behavioral_activation: 0.8
  
  # 正念技术
  # 建议范围: 0.5-0.8
  # 物理意义: 人类指导的正念练习效果更好
  mindfulness_techniques: 0.6
  
  # 解决导向治疗
  # 建议范围: 0.6-0.9
  # 物理意义: 人类治疗师的问题解决能力
  solution_focused_therapy: 0.7
  
  # 心理教育
  # 建议范围: 0.4-0.7
  # 物理意义: 人类治疗师能提供更生动的教育
  psychoeducation: 0.5

# 患者回应分析权重（人类治疗师场景）
patient_response_analysis:
  description: "患者回应分析权重"
  
  # 积极指标权重
  positive_indicators_weight:
    # 感谢表达
    # 建议范围: 0.8-1.0
    # 物理意义: 对人类治疗师感谢的特殊价值
    gratitude_expressions: 0.9
    
    # 洞察陈述
    # 建议范围: 0.9-1.0
    # 物理意义: 人类引导下的洞察更有价值
    insight_statements: 1.0
    
    # 改变承诺
    # 建议范围: 0.7-1.0
    # 物理意义: 对人类治疗师的承诺更有意义
    commitment_to_change: 0.8
    
    # 情感开放
    # 建议范围: 0.6-0.9
    # 物理意义: 向人类治疗师的情感开放更珍贵
    emotional_openness: 0.7
  
  # 消极指标权重（负值）
  negative_indicators_weight:
    # 阻抗表达
    # 建议范围: -0.4到-0.8
    # 物理意义: 对人类治疗师的阻抗影响更大
    resistance_expressions: -0.6
    
    # 绝望陈述
    # 建议范围: -0.6到-1.0
    # 物理意义: 在人类面前表达绝望的严重性
    hopelessness_statements: -0.8
    
    # 退缩行为
    # 建议范围: -0.3到-0.7
    # 物理意义: 从人类治疗师处退缩的负面影响
    withdrawal_behaviors: -0.5
    
    # 治疗贬低
    # 建议范围: -0.5到-0.9
    # 物理意义: 贬低人类治疗师的严重性
    therapy_devaluation: -0.7

# 恢复里程碑设置（人类治疗师场景）
recovery_milestones:
  description: "恢复里程碑设置"
  
  # 早期阶段
  early_stage:
    # CAD改善阈值
    # 建议范围: 1.0-2.0
    # 物理意义: 人类治疗师能更快达到早期改善
    cad_improvement_threshold: 1.2
    
    # 所需会话数
    # 建议范围: 2-4次
    # 物理意义: 人类治疗师的高效性
    session_count: 3
  
  # 中期阶段
  middle_stage:
    # CAD改善阈值
    # 建议范围: 2.5-4.0
    # 物理意义: 中期恢复的累积改善要求
    cad_improvement_threshold: 3.0
    
    # 所需会话数
    # 建议范围: 6-10次
    # 物理意义: 人类治疗师的中期治疗效率
    session_count: 8
  
  # 高级阶段
  advanced_stage:
    # CAD改善阈值
    # 建议范围: 4.0-6.0
    # 物理意义: 高级恢复的累积改善要求
    cad_improvement_threshold: 5.0
    
    # 所需会话数
    # 建议范围: 12-18次
    # 物理意义: 达到高级恢复的会话需求
    session_count: 15

# 治疗阈值设定（人类治疗师场景）
therapy_thresholds:
  # 突破阈值
  # 建议范围: 7.0-10.0
  # 物理意义: 人类治疗师产生治疗突破的CAD阈值
  breakthrough_threshold: 8.5
  
  # 阻抗阈值
  # 建议范围: 2.0-4.0
  # 物理意义: 人类治疗师面对阻抗的容忍度
  resistance_threshold: 2.5
  
  # 联盟建立阈值
  # 建议范围: 5.0-8.0
  # 物理意义: 人类治疗师建立联盟的标准
  alliance_building_threshold: 6.5
  
  # 危机干预阈值
  # 建议范围: 1.0-2.5
  # 物理意义: 人类治疗师的危机干预敏感度
  crisis_intervention_threshold: 1.5

# 状态边界设定（人类治疗师场景）
state_bounds:
  # 最小CAD值
  # 建议范围: -15.0到-5.0
  # 物理意义: CAD状态的最低可能值
  min_cad_value: -10.0
  
  # 最大CAD值
  # 建议范围: 5.0到15.0
  # 物理意义: CAD状态的最高可能值
  max_cad_value: 10.0
  
  # 最小抑郁改善
  # 建议范围: 0.1-0.4
  # 物理意义: 人类治疗师单次会话的最小改善
  min_depression_improvement: 0.2
  
  # 每次会话最大抑郁变化
  # 建议范围: 0.8-2.0
  # 物理意义: 人类治疗师单次会话的最大影响
  max_depression_change_per_session: 1.2 