# 心理健康模拟基础参数配置
# 此文件控制抑郁症模拟的核心参数

description: "心理健康模拟基础参数配置"

# 模拟相关设置
simulation:
  # 模拟持续天数
  # 建议范围: 1-30天
  # 物理意义: 模拟抑郁症发展的时间跨度
  # 较短时间适合快速测试，较长时间更接近真实发展过程
  simulation_days: 30
  
  # 每天产生的事件数量
  # 建议范围: 1-5个
  # 物理意义: 影响主角心理状态的日常事件频率
  # 较多事件可能导致状态变化过快，较少事件可能显得不够丰富
  events_per_day: 3
  
  # 模拟速度倍率
  # 建议范围: 0.5-3.0
  # 物理意义: 控制心理状态变化的快慢
  # 1.0为标准速度，>1.0变化更快，<1.0变化更慢
  simulation_speed: 1
  
  # 抑郁发展阶段数
  # 建议范围: 3-7个阶段
  # 物理意义: 将抑郁症发展分为不同严重程度的阶段
  # 更多阶段提供更细粒度的状态变化
  depression_development_stages: 5
  
  # 社交互动频率
  # 建议范围: 1-5次/天
  # 物理意义: 主角与其他角色互动的频率
  # 影响社交支持和人际关系的发展
  interaction_frequency: 3

# 日志记录设置
logging:
  # 日志级别
  # 可选值: "DEBUG", "INFO", "WARNING", "ERROR"
  # DEBUG: 最详细，包含所有调试信息
  # INFO: 一般信息，推荐用于生产环境
  # WARNING: 仅警告和错误
  # ERROR: 仅错误信息
  log_level: "INFO"
  
  # 是否保存每日状态
  # true: 每天结束时保存详细状态信息
  # false: 仅保存最终状态
  # 建议开启以便后续分析和治疗
  save_daily_states: true
  
  # 是否启用调试模式
  # true: 输出详细的内部状态变化过程
  # false: 仅输出必要信息
  # 调试时开启，正常使用时关闭
  enable_debug_mode: false

# 恢复相关设置
recovery:
  # 改善阈值
  # 建议范围: 5.0-10.0
  # 物理意义: CAD状态改善多少分被认为有显著进步
  # 较低阈值更容易触发改善判定
  improvement_threshold: 7.0
  
  # 治疗联盟阈值
  # 建议范围: 4.0-8.0
  # 物理意义: 患者与治疗师关系质量的最低要求
  # 影响治疗效果和患者配合度
  alliance_threshold: 6.0
  
  # 评估间隔（天）
  # 建议范围: 3-7天
  # 物理意义: 多久进行一次恢复状态评估
  # 较短间隔更敏感，较长间隔更稳定
  evaluation_interval: 5
  
  # 恶化阈值
  # 建议范围: 2.0-5.0
  # 物理意义: CAD状态恶化多少分触发预警
  # 较低阈值对恶化更敏感
  deterioration_threshold: 3.0 